# Generated by Django 5.2.7 on 2025-11-12 03:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome_completo', models.CharField(blank=True, max_length=200, verbose_name='Nome completo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('site', models.URLField(blank=True)),
                ('telefone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'editora',
                'indexes': [models.Index(fields=['nome'], name='editora_nome_d9276c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Escritor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('bibliografia', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='escritores/fotos/')),
            ],
            options={
                'db_table': 'escritor',
                'indexes': [models.Index(fields=['nome'], name='escritor_nome_39c39a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('ano_publicacao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numero_paginas', models.PositiveIntegerField(blank=True, null=True)),
                ('capa', models.ImageField(blank=True, upload_to='livros/capas/')),
                ('nota_media', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_avaliacoes', models.PositiveIntegerField(default=0)),
                ('editora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leia_bem.editora')),
                ('escritor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='leia_bem.escritor')),
            ],
            options={
                'db_table': 'livro',
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='leia_bem.livro')),
            ],
            options={
                'db_table': 'avaliacao',
            },
        ),
        migrations.CreateModel(
            name='ProgressoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagina_atual', models.PositiveIntegerField(default=0)),
                ('porcentagem', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('pontos', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('LENDO', 'Lendo'), ('CONCLUIDO', 'Concluído'), ('PAUSADO', 'Pausado')], default='LENDO', max_length=10)),
                ('atualizado', models.DateTimeField(auto_now=True)),
                ('inicio_progresso', models.DateTimeField(blank=True, null=True)),
                ('ultima_sessao', models.DateTimeField(blank=True, null=True)),
                ('total_sessoes', models.PositiveIntegerField(default=0)),
                ('maior_sequencia_diaria', models.PositiveIntegerField(default=0)),
                ('sequencia_atual', models.PositiveIntegerField(default=0)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leia_bem.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'progresso_leitura',
            },
        ),
        migrations.AddIndex(
            model_name='livro',
            index=models.Index(fields=['titulo'], name='livro_titulo_f7dc59_idx'),
        ),
        migrations.AddIndex(
            model_name='avaliacao',
            index=models.Index(fields=['usuario', 'livro'], name='avaliacao_usuario_edea05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='avaliacao',
            unique_together={('usuario', 'livro')},
        ),
        migrations.AddIndex(
            model_name='progressoleitura',
            index=models.Index(fields=['usuario', 'livro'], name='progresso_l_usuario_6b5be1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='progressoleitura',
            unique_together={('usuario', 'livro')},
        ),
    ]
