# Generated by Django 5.2.7 on 2025-11-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_bem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escritor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
