# Generated by Django 5.2.7 on 2025-11-14 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leia_bem', '0003_livro_isbn_livro_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressoleitura',
            name='pontos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
